import type { Metadata } from "next";
import Link from "next/link";
import Logo from "@/components/ui/Logo";

export const metadata: Metadata = {
  title: "Terms of Use | InstantVerdict",
  description: "Terms of Use for InstantVerdict — AI-powered dispute resolution. Read our terms before using the service.",
  alternates: { canonical: "https://instantverdict.com/terms" },
};

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-white">
      <header className="border-b border-[#E5E7EB] py-4 px-6">
        <Link href="/"><Logo size="sm" /></Link>
      </header>
      <main className="max-w-3xl mx-auto px-6 py-16">
        <h1 className="text-4xl font-black mb-2">Terms of Use</h1>
        <p className="text-[#9CA3AF] text-sm mb-12">Last updated: May 2026</p>

        <div className="prose prose-sm max-w-none space-y-8 text-[#374151] leading-relaxed">

          <section>
            <h2 className="text-xl font-black text-[#0A0A0A] mb-3">1. General</h2>
            <p>InstantVerdict (&ldquo;the Service&rdquo;) is an AI-powered platform that provides general guidance on legal disputes and everyday arguments. By accessing or using instantverdict.com, you agree to these Terms of Use. If you disagree, please do not use the Service.</p>
          </section>

          <section>
            <h2 className="text-xl font-black text-[#0A0A0A] mb-3">2. Not Legal Advice</h2>
            <p>InstantVerdict is <strong>not a law firm</strong> and does not provide legal advice. The verdicts generated by InstantVerdict are for general informational and entertainment purposes only. They do not constitute legal advice, create an attorney-client relationship, or replace advice from a qualified solicitor or attorney.</p>
            <p className="mt-3">Always consult a licensed legal professional for matters with real legal consequences.</p>
          </section>

          <section>
            <h2 className="text-xl font-black text-[#0A0A0A] mb-3">3. Use of the Service</h2>
            <p>You may use InstantVerdict for lawful purposes only. You must not:</p>
            <ul className="list-disc pl-6 mt-2 space-y-1">
              <li>Submit false, misleading, or defamatory content</li>
              <li>Use the Service to harass, threaten, or harm others</li>
              <li>Attempt to reverse-engineer, scrape, or abuse the Service</li>
              <li>Use automated tools to generate bulk requests</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-black text-[#0A0A0A] mb-3">4. Payments</h2>
            <p>Certain features (full verdict unlock) require payment. All payments are processed securely. We do not store payment card details. Refunds may be issued at our discretion for failed transactions.</p>
          </section>

          <section>
            <h2 className="text-xl font-black text-[#0A0A0A] mb-3">5. Intellectual Property</h2>
            <p>All content, design, code, and branding on InstantVerdict is owned by InstantVerdict and protected by copyright. The AI-generated verdicts are provided for your personal use only and may not be resold or redistributed.</p>
          </section>

          <section>
            <h2 className="text-xl font-black text-[#0A0A0A] mb-3">6. Limitation of Liability</h2>
            <p>To the maximum extent permitted by law, InstantVerdict shall not be liable for any indirect, incidental, or consequential damages arising from use of the Service. The Service is provided &ldquo;as is&rdquo; without warranties of any kind.</p>
          </section>

          <section>
            <h2 className="text-xl font-black text-[#0A0A0A] mb-3">7. Changes to These Terms</h2>
            <p>We may update these Terms at any time. Continued use of the Service after changes constitutes acceptance of the new Terms.</p>
          </section>

          <section>
            <h2 className="text-xl font-black text-[#0A0A0A] mb-3">8. Contact</h2>
            <p>For questions about these Terms, contact us via our website.</p>
          </section>
        </div>

        <div className="mt-16 pt-8 border-t border-[#E5E7EB] flex gap-4 text-sm">
          <Link href="/privacy" className="text-[#FF3B30] font-semibold hover:underline">Privacy Policy</Link>
          <Link href="/" className="text-[#6B7280] hover:text-[#0A0A0A]">← Home</Link>
        </div>
      </main>
    </div>
  );
}
